name: torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2020.12.5=py36h5fab9bb_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - dataclasses=0.7=py36_0
  - dbus=1.13.6=he372182_0
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.2.1=h58526e2_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2020.2=254
  - jasper=2.0.14=h07fcdf6_1
  - joblib=0.17.0=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py36h51d7077_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=1_h6e990d7_netlib
  - libcblas=3.9.0=3_h893e4fe_netlib
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libglu=9.0.0=he1b5a44_1001
  - liblapack=3.9.0=3_h893e4fe_netlib
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - matplotlib=3.3.3=py36h5fab9bb_0
  - matplotlib-base=3.3.3=py36he12231b_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py36hff7bd54_0
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1h=h516909a_0
  - pcre=8.44=he1b5a44_0
  - pillow=8.0.1=py36he98fc37_0
  - pip=20.3=py36h06a4308_0
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=3.4.2=py36hb342d67_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py36hcca6a23_4
  - python=3.6.12=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.7.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - scikit-learn=0.23.2=py36hb6e6923_3
  - scipy=1.5.3=py36h976291a_0
  - setuptools=50.3.2=py36h06a4308_2
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.7.0=py36
  - torchvision=0.8.1=py36_cu101
  - tornado=6.1=py36h1d69622_0
  - tqdm=4.54.1=pyhd8ed1ab_0
  - typing_extensions=3.7.4.3=py_0
  - wheel=0.36.0=pyhd3eb1b0_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - future==0.18.2
    - kornia==0.4.1
    - protobuf==3.14.0
    - tensorboardx==2.1

