name: tf_torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py36_0
  - cffi=1.14.0=py36he30daa8_1
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.2=he06d7ca_0
  - glib=2.65.0=h3eb4bd4_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=hf484d3e_1000
  - imageio=2.8.0=py_0
  - intel-openmp=2020.1=217
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - kiwisolver=1.2.0=py36hdb11119_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he1b5a44_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py36hef1b27d_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.1.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.2.0=py36h8328e55_0
  - pip=20.1.1=py36_1
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.20=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py36hcca6a23_4
  - python=3.6.10=h7579374_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.5.1=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pyyaml=5.3.1=py36h8c4c3a4_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - scikit-learn=0.23.1=py36h423224d_0
  - scipy=1.5.0=py36h0b6359f_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.32.3=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.6.1=py36_cu101
  - tornado=6.0.4=py36h8c4c3a4_1
  - tqdm=4.47.0=pyh9f0ad1d_0
  - wheel=0.34.2=py36_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.6=py_0
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - bimpy==0.0.13
    - dareblopy==0.0.3
    - gast==0.3.3
    - grpcio==1.30.0
    - h5py==2.10.0
    - importlib-metadata==1.7.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - mock==4.0.2
    - numpy==1.14.5
    - protobuf==3.12.2
    - setuptools==39.1.0
    - tensorboard==1.13.1
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.13.1
    - termcolor==1.1.0
    - werkzeug==1.0.1
    - zipp==3.1.0
prefix: /home/tal/anaconda3/envs/tf_torch

